const citizens = [

    {
        name: 'aeon flux',
        nationality: 'monica',
        is_spy: true,
        requiresInvestigation: true,
        citizenProfileImage: "https://i.imgur.com/zNFfivd.jpg",
    },
    {
        name: 'trevor goodchild',
        nationality: 'breen',
        is_spy: false,
        requiresInvestigation: false,
        citizenProfileImage: "https://i.imgur.com/r7lZyIO.jpg",
    },
    {
        name: 'una',
        nationality: 'monica',
        is_spy: false,
        requiresInvestigation: true,
        citizenProfileImage: "https://i.imgur.com/HmsC3Nd.jpg",
    },
    {
        name: 'gildemere',
        nationality: 'breen',
        is_spy: false,
        requiresInvestigation: false,
        citizenProfileImage: "https://i.imgur.com/t5BTy6P.jpg",
    },
    {
        name: 'bargeld',
        nationality: 'breen',
        is_spy: false,
        requiresInvestigation: false,
        citizenProfileImage: "https://i.imgur.com/GN2zWZK.jpg",
    },
    {
        name: 'lindze',
        nationality: 'breen',
        is_spy: false,
        requiresInvestigation: false,
        citizenProfileImage: "https://i.imgur.com/u3NyhmN.jpg",
    },
    {
        name: 'rordy',
        nationality: 'breen',
        is_spy: false,
        requiresInvestigation: false,
        citizenProfileImage: "https://i.imgur.com/EFDxTEq.jpg",
    },
    {
        name: 'scaphandra',
        nationality: 'unknown',
        is_spy: true,
        requiresInvestigation: true,
        citizenProfileImage: "https://i.imgur.com/KiyeUEG.jpg",
    },
    {
        name: 'ilbren',
        nationality: 'unknown',
        is_spy: false,
        requiresInvestigation: true,
        citizenProfileImage: "https://i.imgur.com/ZoW2Rd1.jpg",
    },
    {
        name: 'muriel',
        nationality: 'breen',
        is_spy: false,
        requiresInvestigation: true,
        citizenProfileImage: "https://i.imgur.com/7PF4g5C.jpg",
    },
    {
        name: 'naric',
        nationality: 'breen',
        is_spy: false,
        requiresInvestigation: false,
        citizenProfileImage: "https://i.imgur.com/kbprNp4.jpg",
    },
    {
        name: 'president clavius',
        nationality: 'breen',
        is_spy: false,
        requiresInvestigation: true,
        citizenProfileImage: "https://i.imgur.com/xAEZKOT.jpg",
    },
    {
        name: 'emon',
        nationality: 'monica',
        is_spy: true,
        requiresInvestigation: true,
        citizenProfileImage: "https://i.imgur.com/VBojRsL.jpg",
    },
    {
        name: 'number 16',
        nationality: 'breen',
        is_spy: true,
        requiresInvestigation: false,
        citizenProfileImage: "https://i.imgur.com/M7MNsjT.jpg",
    },
    {
        name: 'nader zeneth',
        nationality: 'monica',
        is_spy: true,
        requiresInvestigation: false,
        citizenProfileImage: "https://i.imgur.com/IbNH70r.jpg",
    },
    {
        name: 'celia',
        nationality: 'monica',
        is_spy: true,
        requiresInvestigation: false,
        citizenProfileImage: "https://i.imgur.com/1Jvjyoj.jpg",
    },
    {
        name: 'rubio',
        nationality: 'breen',
        is_spy: true,
        requiresInvestigation: false,
        citizenProfileImage: "https://i.imgur.com/XfIMccw.jpg",
    },
    {
        name: 'the demiurge',
        nationality: 'unknown',
        is_spy: false,
        requiresInvestigation: false,
        citizenProfileImage: "https://i.imgur.com/RfndGyP.jpg",
    },
    {
        name: 'unknown monican agent',
        nationality: 'unknown',
        is_spy: true,
        requiresInvestigation: true,
        citizenProfileImage: "https://i.imgur.com/MpYFpcU.jpg",
    },
    
]

module.exports = citizens