const citizens = [

    {
        name: 'aeon flux',
        nationality: 'monica',
        is_spy: true,
        skills: "espionage, infiltration, mathematics, leadership",
        charges: "sabotoge, destabilization, inducement",
        requiresInvestigation: true,
        citizenProfileImage: "https://i.imgur.com/zNFfivd.jpg",
    },
    {
        name: 'trevor goodchild',
        nationality: 'breen',
        is_spy: false,
        skills: "strategy, invention, leadership, indoctrination",
        charges: "deposition, unauthorized use of government property",
        requiresInvestigation: false,
        citizenProfileImage: "https://i.imgur.com/r7lZyIO.jpg",
    },
    {
        name: 'una',
        nationality: 'monica',
        is_spy: false,
        skills: "translation, rapid comprehension",
        charges: "monican agent",
        requiresInvestigation: false,
        requiresInvestigation: true,
        citizenProfileImage: "https://i.imgur.com/HmsC3Nd.jpg",
    },
    {
        name: 'gildemere',
        nationality: 'breen',
        is_spy: false,
        skills: "inquisitive, partizan",
        charges: "undermining the chairman's leadership",
        requiresInvestigation: false,
        citizenProfileImage: "https://i.imgur.com/t5BTy6P.jpg",
    },
    {
        name: 'bargeld',
        nationality: 'breen',
        is_spy: false,
        skills: "intellect, innovation, resourceful",
        charges: "disobeying direct orders, escape",
        requiresInvestigation: false,
        citizenProfileImage: "https://i.imgur.com/GN2zWZK.jpg",
    },
    {
        name: 'lindze',
        nationality: 'breen',
        is_spy: false,
        skills: "loyalty, tenacity, awareness",
        charges: "aiding with bargeld's escape",
        requiresInvestigation: false,
        citizenProfileImage: "https://i.imgur.com/u3NyhmN.jpg",
    },
    {
        name: 'rordy',
        nationality: 'breen',
        is_spy: false,
        skills: "industrious, perseverant",
        charges: "",
        requiresInvestigation: false,
        citizenProfileImage: "https://i.imgur.com/EFDxTEq.jpg",
    },
    {
        name: 'scaphandra',
        nationality: 'unknown',
        is_spy: true,
        skills: "infiltration, espionage",
        charges: "confidential",
        requiresInvestigation: true,
        citizenProfileImage: "https://i.imgur.com/KiyeUEG.jpg",
    },
    {
        name: 'ilbren',
        nationality: 'unknown',
        is_spy: false,
        skills: "invention, infiltration",
        charges: "unknown",
        requiresInvestigation: true,
        citizenProfileImage: "https://i.imgur.com/ZoW2Rd1.jpg",
    },
    {
        name: 'muriel',
        nationality: 'breen',
        is_spy: false,
        skills: "unknown",
        charges: "unknown",
        requiresInvestigation: true,
        citizenProfileImage: "https://i.imgur.com/7PF4g5C.jpg",
    },
    {
        name: 'naric',
        nationality: 'breen',
        is_spy: false,
        skills: "unknown",
        charges: "none",
        requiresInvestigation: false,
        citizenProfileImage: "https://i.imgur.com/kbprNp4.jpg",
    },
    {
        name: 'president clavius',
        nationality: 'breen',
        is_spy: false,
        skills: "rhetoric",
        charges: "money laundering, sell-enrichment, deception",
        requiresInvestigation: true,
        citizenProfileImage: "https://i.imgur.com/xAEZKOT.jpg",
    },
    {
        name: 'emon',
        nationality: 'monica',
        is_spy: true,
        skills: "espionage",
        charges: "espionage",
        requiresInvestigation: true,
        citizenProfileImage: "https://i.imgur.com/VBojRsL.jpg",
    },
    {
        name: 'number 16',
        nationality: 'breen',
        is_spy: true,
        skills: "combat, determination",
        charges: "none",
        requiresInvestigation: false,
        citizenProfileImage: "https://i.imgur.com/M7MNsjT.jpg",
    },
    {
        name: 'nader zeneth',
        nationality: 'monica',
        is_spy: true,
        skills: "combat, earnest",
        charges: "monican agent",
        requiresInvestigation: false,
        citizenProfileImage: "https://i.imgur.com/IbNH70r.jpg",
    },
    {
        name: 'celia',
        nationality: 'monica',
        is_spy: true,
        skills: "cunning, fortitude",
        charges: "none",
        requiresInvestigation: false,
        citizenProfileImage: "https://i.imgur.com/1Jvjyoj.jpg",
    },
    {
        name: 'rubio',
        nationality: 'breen',
        is_spy: true,
        skills: "combat, loyalty,",
        charges: "none",
        requiresInvestigation: false,
        citizenProfileImage: "https://i.imgur.com/XfIMccw.jpg",
    },
    {
        name: 'the demiurge',
        nationality: 'unknown',
        is_spy: false,
        skills: "unknown",
        charges: "confidential",
        requiresInvestigation: false,
        citizenProfileImage: "https://i.imgur.com/RfndGyP.jpg",
    },
    {
        name: 'unknown monican agent',
        nationality: 'unknown',
        is_spy: true,
        skills: "espionage, infiltration",
        charges: "unknown",
        requiresInvestigation: true,
        citizenProfileImage: "https://i.imgur.com/MpYFpcU.jpg",
    },
    
]

module.exports = citizens